In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\PC\Desktop\project\Ai Adoption\archive 2025\AI_Adoption_2025_Clean.csv",low_memory=False)

In [2]:
df.head(30)

,Age,Country,Employment,MainBranch,AISelect,AISent,AIAcc,AIComplex,AIAgents,AI_Usage_Group,Sentiment_Group,Trust_Group,AI_Capability_Group,Agent_Adoption_Group
0,25-34 years old,Ukraine,Employed,I am a developer by profession,"Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,"Yes, I use AI agents at work monthly or infreq...",Occasional User,Neutral,Neutral,Poor,Active User
1,25-34 years old,Netherlands,Employed,I am a developer by profession,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,"No, and I don't plan to",Weekly User,Neutral,Neutral,Poor,Non User
2,35-44 years old,Ukraine,"Independent contractor, freelancer, or self-em...",I am a developer by profession,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,"Yes, I use AI agents at work weekly",Daily User,Positive,Trust,Neutral,Active User
3,35-44 years old,Ukraine,Employed,I am a developer by profession,"Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,"Yes, I use AI agents at work monthly or infreq...",Weekly User,Positive,Trust,Poor,Active User
4,35-44 years old,Ukraine,"Independent contractor, freelancer, or self-em...",I am a developer by profession,"Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks","No, and I don't plan to",Weekly User,Positive,Neutral,Good,Non User
5,45-54 years old,Ukraine,"Independent contractor, freelancer, or self-em...",I am a developer by profession,"Yes, I use AI tools daily",Indifferent,Somewhat distrust,"Good, but not great at handling complex tasks","Yes, I use AI agents at work monthly or infreq...",Daily User,Neutral,Distrust,Good,Active User
6,25-34 years old,Ukraine,"Independent contractor, freelancer, or self-em...",I am a developer by profession,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,"Yes, I use AI agents at work monthly or infreq...",Daily User,Positive,Trust,Neutral,Active User
7,35-44 years old,Ukraine,Employed,I am a developer by profession,"Yes, I use AI tools daily",Very favorable,Somewhat trust,Neither good or bad at handling complex tasks,"No, but I plan to",Daily User,Positive,Trust,Neutral,Future User
8,25-34 years old,Ukraine,Employed,I am a developer by profession,"Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Neither good or bad at handling complex tasks,No Response,Occasional User,Neutral,Neutral,Neutral,No Response
9,25-34 years old,Ukraine,Employed,I am a developer by profession,"No, and I don't plan to",Unfavorable,Highly distrust,Very poor at handling complex tasks,"No, but I plan to",Non User,Negative,Distrust,Poor,Future User
10,25-34 years old,Ukraine,Employed,I am a developer by profession,"Yes, I use AI tools daily",Very favorable,Somewhat distrust,Very poor at handling complex tasks,"Yes, I use AI agents at work daily",Daily User,Positive,Distrust,Poor,Active User
11,18-24 years old,Ukraine,Employed,I am a developer by profession,"Yes, I use AI tools daily",Very favorable,Neither trust nor distrust,Bad at handling complex tasks,"No, but I plan to",Daily User,Positive,Neutral,Poor,Future User
12,35-44 years old,Ukraine,"Independent contractor, freelancer, or self-em...",I am a developer by profession,"Yes, I use AI tools monthly or infrequently",Unfavorable,Somewhat distrust,Bad at handling complex tasks,"No, and I don't plan to",Occasional User,Negative,Distrust,Poor,Non User
13,25-34 years old,India,Employed,I am a developer by profession,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response,No Response
14,35-44 years old,Georgia,Employed,I am a developer by profession,"Yes, I use AI tools daily",Favorable,Somewhat trust,"Good, but not great at handling complex tasks","No, and I don't plan to",Daily User,Positive,Trust,Good,Non User
15,18-24 years old,India,Student,I am a developer by profession,"Yes, I use AI tools daily",Favorable,Highly trust,"Good, but not great at handling complex tasks","Yes, I use AI agents at work daily",Daily User,Positive,Trust,Good,Active User
16,65 years or older,Australia,Retired,"I am not primarily a developer, but I write co...","No, and I don't plan to",Very unfavorable,Highly distrust,I don't use AI tools for complex tasks / I don...,"No, and I don't plan to",Non User,Negative,Distrust,Unknown,Non User
17,25-34 years old,Greece,Employed,I am a developer by profession,"Yes, I use AI tools daily",Unfavorable,Neither trust nor distrust,"Good, but not great at handling complex tasks","No, and I don't plan to",Daily User,Negative,Neutral,Good,Non User
18,35-44 years old,Germany,Employed,I am a developer by profession,"No, and I don't plan to",Very unfavorable,Highly distrust,Very poor at handling complex tasks,"No, and I don't plan to",Non User,Negative,Distrust,Poor,Non User
19,25-34 years old,Bangladesh,"Independent contractor, freelancer, or self-em...","I am not primarily a developer, but I write co...","Yes, I use AI tools daily",Very favorable,Neither trust nor distrust,Very well at handling complex tasks,"No, but I plan to",Daily User,Positive,Neutral,Good,Future User
20,55-64 years old,Brazil,Employed,"I am not primarily a developer, but I write co...","No, and I don't plan to",Unfavorable,Highly distrust,I don't use AI tools for complex tasks / I don...,"No, and I don't plan to",Non User,Negative,Distrust,Unknown,Non User
21,45-54 years old,United States of America,Employed,"I am not primarily a developer, but I write co...","No, and I don't plan to",Very unfavorable,Highly distrust,I don't use AI tools for complex tasks / I don...,"No, and I don't plan to",Non User,Negative,Distrust,Unknown,Non User
22,25-34 years old,United States of America,Employed,I am a developer by profession,"Yes, I use AI tools monthly or infrequently",Unfavorable,Somewhat distrust,Bad at handling complex tasks,"No, and I don't plan to",Occasional User,Negative,Distrust,Poor,Non User
23,18-24 years old,Netherlands,Employed,I am a developer by profession,"No, and I don't plan to",Very unfavorable,Somewhat distrust,Very poor at handling complex tasks,"No, and I don't plan to",Non User,Negative,Distrust,Poor,Non User
24,65 years or older,Lithuania,"Independent contractor, freelancer, or self-em...",I am a developer by profession,"No, and I don't plan to",Very unfavorable,Highly distrust,I don't use AI tools for complex tasks / I don...,"No, and I don't plan to",Non User,Negative,Distrust,Unknown,Non User
25,55-64 years old,United Kingdom of Great Britain and Northern I...,"Independent contractor, freelancer, or self-em...",I am a developer by profession,"Yes, I use AI tools daily",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks","Yes, I use AI agents at work weekly",Daily User,Positive,Neutral,Good,Active User
26,45-54 years old,Ireland,"Independent contractor, freelancer, or self-em...",I am a developer by profession,"Yes, I use AI tools daily",Favorable,Somewhat trust,"Good, but not great at handling complex tasks","No, but I plan to",Daily User,Positive,Trust,Good,Future User
27,45-54 years old,Sweden,Employed,I am a developer by profession,"Yes, I use AI tools daily",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,"No, and I don't plan to",Daily User,Neutral,Neutral,Poor,Non User
28,35-44 years old,Dominican Republic,"Independent contractor, freelancer, or self-em...",I am a developer by profession,"Yes, I use AI tools weekly",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,"Yes, I use AI agents at work weekly",Weekly User,Positive,Trust,Neutral,Active User
29,35-44 years old,United States of America,Employed,I am a developer by profession,"Yes, I use AI tools daily",Favorable,Somewhat distrust,Very poor at handling complex tasks,"No, and I don't plan to",Daily User,Positive,Distrust,Poor,Non User

In [10]:
#How frequently do developers use AI?
usage_freq = (
    df['AI_Usage_Group']
    .value_counts(normalize=True)*100
)

usage_freq

AI_Usage_Group
Daily User         32.288427
No Response        31.450875
Weekly User        12.111972
Non User           11.087394
Occasional User     9.408225
Future User         3.653107
Name: proportion, dtype: float64

In [7]:
#Adoption rate
valid = df[df['AI_Usage_Group'] != 'No Response']

ai_users = valid[
    valid['AI_Usage_Group'].isin(
        ['Daily User','Weekly User','Occasional User']
    )
]

adoption_rate = len(ai_users) / len(valid) * 100

print(f"AI Adoption Rate: {adoption_rate:.2f}%")

AI Adoption Rate: 78.50%

In [11]:
#How do developers feel about AI?
sentiment = (
    df['Sentiment_Group']
    .value_counts(normalize=True)*100
)

sentiment

Sentiment_Group
Positive       40.633449
No Response    31.965197
Negative       13.904983
Neutral        13.496371
Name: proportion, dtype: float64

In [13]:
#Positive Sentiment Rate
valid_sent = df[df['Sentiment_Group'] != 'No Response']

positive_rate = (
    (valid_sent['Sentiment_Group'] == 'Positive')
    .mean()*100
)

print(f"Positive Sentiment Rate: {positive_rate:.2f}%")

Positive Sentiment Rate: 59.72%

In [14]:
#Do developers trust AI?
trust = (
    df['Trust_Group']
    .value_counts(normalize=True)*100
)

trust

Trust_Group
No Response    32.310789
Distrust       30.936553
Trust          22.193084
Neutral        14.559574
Name: proportion, dtype: float64

In [15]:
#Trust Rate
valid_trust = df[df['Trust_Group'] != 'No Response']

trust_rate = (
    (valid_trust['Trust_Group'] == 'Trust')
    .mean()*100
)

trust_rate
print(f"Trust Rate: {trust_rate:.2f}%")

Trust Rate: 32.79%

In [16]:
#Do AI users trust AI more?
pd.crosstab(
    df['AI_Usage_Group'],
    df['Trust_Group'],
    normalize='index'
).round(3)*100

Trust_Group      Distrust  Neutral  No Response  Trust
AI_Usage_Group
Daily User           26.1     23.7          1.4   48.7
Future User          47.3     27.4          2.4   22.9
No Response           0.1      0.0         99.8    0.1
Non User             84.7     10.1          1.4    3.9
Occasional User      61.9     19.3          1.4   17.4
Weekly User          45.6     24.3          1.0   29.2

In [17]:
#Are AI agents already being adopted?

agent_usage = (
    df['Agent_Adoption_Group']
    .value_counts(normalize=True)*100
)

agent_usage

Agent_Adoption_Group
No Response     35.112114
Non User        24.561404
Active User     20.074810
Future User     11.304914
Copilot Only     8.946759
Name: proportion, dtype: float64

In [18]:
#Agent Adoption Rate
valid_agents = df[
    df['Agent_Adoption_Group'] != 'No Response'
]

agent_rate = (
    (valid_agents['Agent_Adoption_Group'] == 'Active User')
    .mean()*100
)

agent_rate
print(f"Agent Adoption Rate: {agent_rate:.2f}%")

Agent Adoption Rate: 30.94%

In [19]:
#How capable is AI for complex tasks?
complexity = (
    df['AI_Capability_Group']
    .value_counts(normalize=True)*100
)

complexity

AI_Capability_Group
No Response    32.339249
Poor           26.777256
Good           20.005692
Unknown        11.347604
Neutral         9.530199
Name: proportion, dtype: float64

In [20]:
#Which age groups adopt AI the most?

pd.crosstab(
    df['Age'],
    df['AI_Usage_Group'],
    normalize='index'
).round(3)*100

AI_Usage_Group,Daily User,Future User,No Response,Non User,Occasional User,Weekly User
Age,,,,,,
18-24 years old,28.3,1.6,39.9,10.4,8.2,11.5
25-34 years old,33.9,2.6,33.7,9.4,8.5,11.8
35-44 years old,34.8,3.8,28.5,10.4,9.8,12.6
45-54 years old,34.0,5.5,24.7,11.6,10.9,13.3
55-64 years old,26.9,9.6,20.3,18.5,12.3,12.3
65 years or older,17.8,11.3,19.9,28.8,13.0,9.3
Prefer not to say,15.1,2.4,47.9,18.0,9.5,7.1

In [21]:
#How capable is AI for complex tasks?
age_group = (
    df['Age']
    .value_counts(normalize=True)*100
)

age_group

Age
25-34 years old      33.581346
35-44 years old      26.917526
18-24 years old      18.722937
45-54 years old      12.756399
55-64 years old       5.338375
65 years or older     1.914984
Prefer not to say     0.768433
Name: proportion, dtype: float64

In [22]:
#Which age groups adopt AI the most? only users 

ai_users_only = df[
    df['AI_Usage_Group'].isin([
        'Daily User',
        'Weekly User',
        'Occasional User'
    ])
]

pd.crosstab(
    ai_users_only['Age'],
    ai_users_only['AI_Usage_Group'],
    normalize='index'
).round(3) * 100

AI_Usage_Group     Daily User  Occasional User  Weekly User
Age
18-24 years old          59.0             17.1         23.9
25-34 years old          62.5             15.7         21.8
35-44 years old          60.8             17.1         22.0
45-54 years old          58.3             18.8         22.9
55-64 years old          52.2             23.9         23.9
65 years or older        44.4             32.3         23.3
Prefer not to say        47.5             30.0         22.5

In [32]:
#Adoption rate by age:

adoption_by_age = pd.crosstab(
    df['Age'],
    df['AI_Usage_Group']
)

adoption_by_age['AI Adoption Rate'] = (
    (
        adoption_by_age['Daily User']
        + adoption_by_age['Weekly User']
        + adoption_by_age['Occasional User']
    )
    /
    (
        adoption_by_age['Daily User']
        + adoption_by_age['Weekly User']
        + adoption_by_age['Occasional User']
        + adoption_by_age['Future User']
        + adoption_by_age['Non User']
    )
) * 100

adoption_by_age[['AI Adoption Rate']].sort_values(
    'AI Adoption Rate',
    ascending=False
)

AI_Usage_Group     AI Adoption Rate
Age
25-34 years old           81.780009
35-44 years old           80.120482
18-24 years old           79.956624
45-54 years old           77.312169
55-64 years old           64.691830
Prefer not to say         60.913706
65 years or older         50.066225

In [24]:
#Does employment status influence AI adoption?
pd.crosstab(
    df['Employment'],
    df['AI_Usage_Group'],
    normalize='index'
).round(3)*100

AI_Usage_Group,Daily User,Future User,No Response,Non User,Occasional User,Weekly User
Employment,,,,,,
Employed,34.2,3.5,29.1,10.7,9.7,12.9
I prefer not to say,15.4,7.3,48.6,15.1,7.9,5.6
"Independent contractor, freelancer, or self-employed",36.1,3.9,30.1,10.2,8.9,10.7
Not employed,26.9,6.1,33.6,14.2,8.8,10.4
Retired,14.7,12.1,21.9,30.2,12.3,8.8
Student,25.9,2.1,37.0,12.6,9.7,12.6
Unknown,0.0,0.0,100.0,0.0,0.0,0.0

In [26]:
#Are AI users also adopting AI agents?
pd.crosstab(
    df['AI_Usage_Group'],
    df['Agent_Adoption_Group'],
    normalize='index'
).round(3)*100

Agent_Adoption_Group,Active User,Copilot Only,Future User,No Response,Non User
AI_Usage_Group,,,,,
Daily User,43.9,15.2,18.0,5.9,17.1
Future User,9.3,9.6,41.7,9.2,30.2
No Response,0.1,0.0,0.0,99.8,0.1
Non User,2.8,2.1,3.0,3.7,88.4
Occasional User,20.1,15.2,14.7,5.3,44.8
Weekly User,27.5,16.7,18.6,5.0,32.2

In [30]:
#Which countries have the highest AI adoption?

pd.crosstab(
    df['Country'],
    df['AI_Usage_Group'],
    normalize='index'
).round(3)*100
#Top 20 countries only
top_countries = (
    df['Country']
    .value_counts()
    .head(20)
    .index
)

country_analysis = pd.crosstab(
    df[df['Country'].isin(top_countries)]['Country'],
    df[df['Country'].isin(top_countries)]['AI_Usage_Group'],
    normalize='index'
)

country_analysis.round(3)*100

AI_Usage_Group,Daily User,Future User,No Response,Non User,Occasional User,Weekly User
Country,,,,,,
Australia,39.8,3.9,3.6,22.4,13.9,16.4
Austria,36.8,3.9,2.0,17.3,18.5,21.5
Belgium,36.4,5.3,3.4,15.6,17.4,21.8
Brazil,52.0,4.6,4.2,8.8,13.0,17.3
Canada,38.3,4.8,4.4,20.8,14.6,17.0
Czech Republic,48.8,4.4,3.8,13.8,11.9,17.1
France,35.3,3.9,3.7,22.9,16.8,17.4
Germany,39.8,4.6,3.1,18.6,15.1,18.8
India,53.8,6.9,10.7,4.9,10.3,13.3
Italy,45.3,4.7,4.0,13.4,13.3,19.4
Netherlands,42.7,5.1,2.4,15.6,15.3,18.9
Poland,47.0,2.9,4.7,15.1,13.7,16.6
Romania,44.9,4.0,5.0,12.4,13.3,20.4
Spain,50.2,3.5,4.7,11.4,11.7,18.4
Sweden,41.2,4.4,2.9,17.0,14.8,19.6
Switzerland,42.9,5.1,1.8,15.6,13.0,21.6
Ukraine,57.9,3.9,5.1,5.6,9.5,17.9
United Kingdom of Great Britain and Northern Ireland,34.6,4.9,3.6,26.7,14.5,15.6
United States of America,38.1,5.7,4.1,20.8,14.1,17.1
Unknown Country,0.0,0.0,100.0,0.0,0.0,0.0

In [31]:
#KPI Summary Table
kpis = {
    'Total Respondents': len(df),
    'AI Adoption Rate': round(adoption_rate,2),
    'Positive Sentiment Rate': round(positive_rate,2),
    'Trust Rate': round(trust_rate,2),
    'Agent Adoption Rate': round(agent_rate,2)
}

pd.DataFrame(
    kpis.items(),
    columns=['KPI','Value']
)

                       KPI     Value
0        Total Respondents  49191.00
1         AI Adoption Rate     78.50
2  Positive Sentiment Rate     59.72
3               Trust Rate     32.79
4      Agent Adoption Rate     30.94