In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\PC\Desktop\project\Ai Adoption\archive 2024\AI_Adoption_2024_Clean.csv",low_memory=False)

In [2]:
#What is the AI Adoption Rate in 2024?
df['AI_Usage_Group'].value_counts()

AI_Usage_Group
AI User        37662
Non User       14837
Future User     8408
No Response     4530
Name: count, dtype: int64

In [3]:
valid = df[df['AI_Usage_Group'] != 'No Response']

adoption_rate = (
    (valid['AI_Usage_Group'] == 'AI User')
    .mean()
    * 100
)

print(f"AI Adoption Rate: {adoption_rate:.2f}%")

AI Adoption Rate: 61.84%

In [4]:
#What is the distribution of AI users, future users, and non-users?
(
    df['AI_Usage_Group']
    .value_counts(normalize=True)
    * 100
).round(2)

AI_Usage_Group
AI User        57.55
Non User       22.67
Future User    12.85
No Response     6.92
Name: proportion, dtype: float64

In [5]:
#How do developers feel about AI?

(
    df['Sentiment_Group']
    .value_counts(normalize=True)
    * 100
).round(2)

Sentiment_Group
Positive       50.45
No Response    29.90
Neutral        15.16
Negative        4.49
Name: proportion, dtype: float64

In [6]:
#Positive Sentiment Rate
valid_sent = df[
    df['Sentiment_Group'] != 'No Response'
]

positive_rate = (
    (valid_sent['Sentiment_Group'] == 'Positive')
    .mean()
    * 100
)

positive_rate

np.float64(71.97044012817997)

In [7]:
#Do developers trust AI?
(
    df['Trust_Group']
    .value_counts(normalize=True)
    * 100
).round(2)

Trust_Group
No Response    43.00
Trust          24.54
Distrust       17.31
Neutral        15.16
Name: proportion, dtype: float64

In [8]:
#Trust Rate
valid_trust = df[
    df['Trust_Group'] != 'No Response'
]

trust_rate = (
    (valid_trust['Trust_Group'] == 'Trust')
    .mean()
    * 100
)

trust_rate

np.float64(43.04058763605168)

In [9]:
#How capable is AI for complex tasks?
(
    df['AI_Capability_Group']
    .value_counts(normalize=True)
    * 100
).round(2)

AI_Capability_Group
No Response    43.42
Poor           24.45
Good           20.35
Neutral        11.78
Name: proportion, dtype: float64

In [10]:
#Capability Rate
valid_cap = df[
    df['AI_Capability_Group'] != 'No Response'
]

good_rate = (
    (valid_cap['AI_Capability_Group'] == 'Good')
    .mean()
    * 100
)

good_rate

np.float64(35.971475648955995)

In [13]:
#Which age groups adopt AI the most?
pd.crosstab(
    df['Age'],
    df['AI_Usage_Group'],
    normalize='index'
).round(3) * 100

AI_Usage_Group      AI User  Future User  No Response  Non User
Age
18-24 years old        63.7          7.9          9.6      18.9
25-34 years old        60.8         12.0          7.3      19.9
35-44 years old        54.8         15.3          5.5      24.5
45-54 years old        50.5         18.6          4.0      26.9
55-64 years old        39.5         21.4          3.5      35.7
65 years or older      31.1         19.7          3.6      45.6
Prefer not to say      38.2         11.8         14.0      36.0
Under 18 years old     55.9          9.2          7.9      27.1

In [14]:
age_ai = pd.crosstab(
    df['Age'],
    df['AI_Usage_Group']
)

age_ai['AI Adoption Rate'] = (
    age_ai['AI User']
    /
    (
        age_ai['AI User']
        + age_ai['Future User']
        + age_ai['Non User']
    )
) * 100

age_ai[['AI Adoption Rate']]\
.sort_values('AI Adoption Rate', ascending=False)

AI_Usage_Group      AI Adoption Rate
Age
18-24 years old            70.397678
25-34 years old            65.568592
Under 18 years old         60.693153
35-44 years old            57.943925
45-54 years old            52.615795
Prefer not to say          44.404332
55-64 years old            40.885312
65 years or older          32.258065

In [15]:
#Which developer profiles adopt AI the most?

profile_ai = pd.crosstab(
    df['Developer_Profile'],
    df['AI_Usage_Group']
)

profile_ai['AI Adoption Rate'] = (
    profile_ai['AI User']
    /
    (
        profile_ai['AI User']
        + profile_ai['Future User']
        + profile_ai['Non User']
    )
) * 100

profile_ai[['AI Adoption Rate']]\
.sort_values('AI Adoption Rate', ascending=False)

AI_Usage_Group          AI Adoption Rate
Developer_Profile
Learning Developer             66.202091
Professional Developer         63.257422
Occasional Developer           57.547325
Hobbyist                       52.212957
Former Developer               43.754411

In [16]:
#Does AI adoption influence sentiment?

pd.crosstab(
    df['AI_Usage_Group'],
    df['Sentiment_Group'],
    normalize='index'
).round(3) * 100

Sentiment_Group  Negative  Neutral  No Response  Positive
AI_Usage_Group
AI User               5.7     17.4          0.3      76.6
Future User           9.3     40.1          0.8      49.8
No Response           0.0      0.0        100.0       0.0
Non User              0.0      0.0        100.0       0.0

In [17]:
#Does AI adoption influence trust?

pd.crosstab(
    df['AI_Usage_Group'],
    df['Trust_Group'],
    normalize='index'
).round(3) * 100

Trust_Group     Distrust  Neutral  No Response  Trust
AI_Usage_Group
AI User             30.1     26.3          1.0   42.6
Future User          0.0      0.0        100.0    0.0
No Response          0.0      0.0        100.0    0.0
Non User             0.0      0.0        100.0    0.0

In [18]:
#Does AI adoption influence perceived capability?
pd.crosstab(
    df['AI_Usage_Group'],
    df['AI_Capability_Group'],
    normalize='index'
).round(3) * 100

AI_Capability_Group  Good  Neutral  No Response  Poor
AI_Usage_Group
AI User              35.4     20.5          1.7  42.5
Future User           0.0      0.0        100.0   0.0
No Response           0.0      0.0        100.0   0.0
Non User              0.0      0.0        100.0   0.0

In [19]:
#Which countries show the highest AI adoption?
top_countries = (
    df['Country']
    .value_counts()
    .head(15)
    .index
)

country_df = df[
    df['Country'].isin(top_countries)
]

country_ai = pd.crosstab(
    country_df['Country'],
    country_df['AI_Usage_Group']
)

country_ai['AI Adoption Rate'] = (
    country_ai['AI User']
    /
    (
        country_ai['AI User']
        + country_ai['Future User']
        + country_ai['Non User']
    )
) * 100

country_ai[['AI Adoption Rate']]\
.sort_values('AI Adoption Rate', ascending=False)

AI_Usage_Group                                      AI Adoption Rate
Country
Unknown Country                                            79.464286
Ukraine                                                    72.338831
India                                                      67.940399
Brazil                                                     65.983906
Spain                                                      65.291480
Poland                                                     62.967827
Sweden                                                     62.003968
Netherlands                                                60.235947
Canada                                                     58.205374
Italy                                                      57.132132
Germany                                                    57.096314
Australia                                                  54.828412
United States of America                                   54.249614
France                                                     54.202483
United Kingdom of Great Britain and Northern Ir...         50.701153

In [20]:
#kpis table
kpis = {
    'Total Respondents': len(df),
    'AI Adoption Rate': round(adoption_rate,2),
    'Positive Sentiment Rate': round(positive_rate,2),
    'Trust Rate': round(trust_rate,2),
    'AI Capability Rate': round(good_rate,2)
}

pd.DataFrame(
    kpis.items(),
    columns=['KPI','Value']
)

                       KPI     Value
0        Total Respondents  65437.00
1         AI Adoption Rate     61.84
2  Positive Sentiment Rate     71.97
3               Trust Rate     43.04
4       AI Capability Rate     35.97