In [ ]:
import pandas as pd
df = pd.read_csv(r"..\Data_out\AI_Adoption_2023_Clean.csv",low_memory=False)

In [4]:
#What is the AI Adoption Rate in 2023?
valid_users = df[
    df['AI_Usage_Group'] != 'No Response'
]

adoption_rate = (
    (valid_users['AI_Usage_Group'] == 'AI User')
    .mean()
    * 100
)

print(f"AI Adoption Rate: {adoption_rate:.2f}%")

AI Adoption Rate: 44.38%

In [5]:
#How is AI adoption distributed?
(
    df['AI_Usage_Group']
    .value_counts(normalize=True)
    * 100
).round(2)

AI_Usage_Group
AI User        43.78
Non User       29.40
Future User    25.46
No Response     1.36
Name: proportion, dtype: float64

In [6]:
#What is the overall sentiment toward AI?
(
    df['Sentiment_Group']
    .value_counts(normalize=True)
    * 100
).round(2)

Sentiment_Group
Positive       52.60
No Response    31.04
Neutral        14.15
Negative        2.21
Name: proportion, dtype: float64

In [7]:
#Positive Sentiment Rate
valid_sent = df[
    df['Sentiment_Group'] != 'No Response'
]

positive_rate = (
    (valid_sent['Sentiment_Group'] == 'Positive')
    .mean()
    * 100
)

positive_rate

np.float64(76.28006048682136)

In [8]:
#Do developers trust AI?
(
    df['Trust_Group']
    .value_counts(normalize=True)
    * 100
).round(2)

Trust_Group
No Response    31.16
Trust          29.02
Neutral        21.12
Distrust       18.70
Name: proportion, dtype: float64

In [9]:
#Trust Rate
valid_trust = df[
    df['Trust_Group'] != 'No Response'
]

trust_rate = (
    (valid_trust['Trust_Group'] == 'Trust')
    .mean()
    * 100
)

trust_rate

np.float64(42.15095445957392)

In [10]:
#BQ5 — Which age groups adopt AI the most?


age_ai = pd.crosstab(
    df['Age'],
    df['AI_Usage_Group']
)

age_ai['AI Adoption Rate'] = (
    age_ai['AI User']
    /
    (
        age_ai['AI User']
        + age_ai['Future User']
        + age_ai['Non User']
    )
) * 100

age_ai[['AI Adoption Rate']]\
.sort_values('AI Adoption Rate', ascending=False)

AI_Usage_Group      AI Adoption Rate
Age
18-24 years old            56.490493
Under 18 years old         54.306279
25-34 years old            45.921184
35-44 years old            38.938663
45-54 years old            32.598368
Prefer not to say          30.699088
55-64 years old            25.247971
65 years or older          18.318584

In [11]:
#Which developer profiles adopt AI the most?

profile_ai = pd.crosstab(
    df['Developer_Profile'],
    df['AI_Usage_Group']
)

profile_ai['AI Adoption Rate'] = (
    profile_ai['AI User']
    /
    (
        profile_ai['AI User']
        + profile_ai['Future User']
        + profile_ai['Non User']
    )
) * 100

profile_ai[['AI Adoption Rate']]\
.sort_values('AI Adoption Rate', ascending=False)

AI_Usage_Group          AI Adoption Rate
Developer_Profile
Learning Developer             54.867970
Professional Developer         44.167646
Hobbyist                       43.689516
Occasional Developer           42.941702
Former Developer               32.831811
Other                                NaN

In [12]:
#Does AI adoption influence sentiment?
pd.crosstab(
    df['AI_Usage_Group'],
    df['Sentiment_Group'],
    normalize='index'
).round(3) * 100

Sentiment_Group  Negative  Neutral  No Response  Positive
AI_Usage_Group
AI User               2.3     12.8          0.2      84.6
Future User           4.6     33.6          0.7      61.1
No Response           0.0      0.0        100.0       0.0
Non User              0.0      0.0        100.0       0.0

In [13]:
#Does AI adoption influence trust?
pd.crosstab(
    df['AI_Usage_Group'],
    df['Trust_Group'],
    normalize='index'
).round(3) * 100

Trust_Group     Distrust  Neutral  No Response  Trust
AI_Usage_Group
AI User             24.1     27.5          0.4   48.0
Future User         32.0     35.6          0.9   31.5
No Response          0.0      0.0        100.0    0.0
Non User             0.0      0.0        100.0    0.0

In [15]:
#Which countries have the highest AI adoption?

top_countries = (
    df['Country']
    .value_counts()
    .head(15)
    .index
)

country_df = df[
    df['Country'].isin(top_countries)
]

country_ai = pd.crosstab(
    country_df['Country'],
    country_df['AI_Usage_Group']
)

country_ai['AI Adoption Rate'] = (
    country_ai['AI User']
    /
    (
        country_ai['AI User']
        + country_ai['Future User']
        + country_ai['Non User']
    )
) * 100

country_ai[['AI Adoption Rate']]\
.sort_values('AI Adoption Rate', ascending=False)

AI_Usage_Group                                      AI Adoption Rate
Country
Brazil                                                     48.188051
Poland                                                     46.981520
Spain                                                      46.728462
Switzerland                                                46.649260
India                                                      46.400000
Netherlands                                                45.111204
Sweden                                                     42.717855
Germany                                                    41.839520
Australia                                                  41.722810
Canada                                                     41.431423
France                                                     40.300034
United States of America                                   39.470156
United Kingdom of Great Britain and Northern Ir...         37.103746
Italy                                                      36.130790
Unknown Country                                                  NaN

In [16]:
#Which age groups are the most positive toward AI?

sentiment_age = pd.crosstab(
    df['Age'],
    df['Sentiment_Group'],
    normalize='index'
).round(3) * 100

sentiment_age[['Positive']]\
.sort_values('Positive', ascending=False)

Sentiment_Group     Positive
Age
18-24 years old         59.2
25-34 years old         55.1
Under 18 years old      54.0
35-44 years old         49.9
45-54 years old         45.0
55-64 years old         37.7
65 years or older       30.1
Prefer not to say       24.7

In [17]:
#Which developer profiles trust AI the most?
trust_profile = pd.crosstab(
    df['Developer_Profile'],
    df['Trust_Group'],
    normalize='index'
).round(3) * 100

trust_profile[['Trust']]\
.sort_values('Trust', ascending=False)

Trust_Group             Trust
Developer_Profile
Learning Developer       44.9
Hobbyist                 31.2
Occasional Developer     30.8
Professional Developer   28.0
Former Developer         27.5
Other                     0.0

In [19]:
#KPI Summary Table
kpis = {
    'Total Respondents': len(df),
    'AI Adoption Rate': round(adoption_rate,2),
    'Positive Sentiment Rate': round(positive_rate,2),
    'Trust Rate': round(trust_rate,2)
}

pd.DataFrame(
    kpis.items(),
    columns=['KPI','Value']
)

                       KPI     Value
0        Total Respondents  89184.00
1         AI Adoption Rate     44.38
2  Positive Sentiment Rate     76.28
3               Trust Rate     42.15